blank_lines_lower_bound = 1
chain_width = 120
max_width = 120
condense_wildcard_suffixes = true
edition = "2018"
fn_params_layout = "Compressed"
fn_single_line = true
format_macro_matchers = true
format_strings = true
hard_tabs = true
merge_imports = true
newline_style = "Unix"
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true